[package]
name = "gitcal"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
reqwest = { version = "0.12.7", features = ["blocking"] }
serde_json = "1.0.128"
colored = "2.1.0"
hex_color = "3.0.0"
clap = "4.5.17"
